name: Whedon paper build

on:
  push:
    paths:
      - 'paper/**'
  workflow_dispatch:

jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openjournals/whedon-action@v1

