name: Build JOSS Paper

on:
  push:
    paths:
      - 'paper/**'
  workflow_dispatch:

jobs:
  build-paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build paper with Whedon
        uses: openjournals/whedon-action@v1

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
